'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Documents

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''MainMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainMenu As Global.CSBCHOOPS_COM.MainMenu

    '''<summary>
    '''Lnk1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk1 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk2 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk3 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk4 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk5 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk6 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk7 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk26 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk8 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk9 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk10 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk11 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk17 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk12 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk18 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk13 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk19 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk14 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk20 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk15 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk21 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk16 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk22 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk23 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk24 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Lnk25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lnk25 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
End Class
